services:
  # Backend API Service
  - type: web
    name: dhavtr-backend
    env: python
    region: frankfurt
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: https://dhavtr-frontend.onrender.com,https://hancer.av.tr
      - key: DATABASE_URL
        value: sqlite:///./hancer_law.db
      - key: HOST
        value: 0.0.0.0

  # Frontend Static Site
  - type: web
    name: dhavtr-frontend
    env: static
    region: frankfurt
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://dhavtr-backend.onrender.com