version: '3.8'

services:
  backend:
    build: .
    container_name: hancer-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./hancer_law.db:/app/hancer_law.db
    environment:
      - ENVIRONMENT=production
      - PORT=8000
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://13.61.26.90:8000/').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
